# Installing Packages

In [1]:
!pip install data-cleaning

Requirement already satisfied: data-cleaning in c:\users\mural\appdata\local\programs\python\python37\lib\site-packages (1.0.1)
Requirement already satisfied: joblib in c:\users\mural\appdata\local\programs\python\python37\lib\site-packages (from data-cleaning) (1.0.1)
Requirement already satisfied: missingpy in c:\users\mural\appdata\local\programs\python\python37\lib\site-packages (from data-cleaning) (0.2.0)
Requirement already satisfied: python-dateutil in c:\users\mural\appdata\local\programs\python\python37\lib\site-packages (from data-cleaning) (2.8.1)
Requirement already satisfied: numpy in c:\users\mural\appdata\local\programs\python\python37\lib\site-packages (from data-cleaning) (1.19.5)
Requirement already satisfied: scipy in c:\users\mural\appdata\local\programs\python\python37\lib\site-packages (from data-cleaning) (1.6.1)
Requirement already satisfied: six in c:\users\mural\appdata\local\programs\python\python37\lib\site-packages (from data-cleaning) (1.15.0)
Requirement already satisfied: scikit-learn in c:\users\mural\appdata\local\programs\python\python37\lib\site-packages (from data-cleaning) (0.24.1)
Requirement already satisfied: pandas in c:\users\mural\appdata\local\programs\python\python37\lib\site-packages (from data-cleaning) (1.2.3)
Requirement already satisfied: pytz in c:\users\mural\appdata\local\programs\python\python37\lib\site-packages (from data-cleaning) (2021.1)
Requirement already satisfied: threadpoolctl in c:\users\mural\appdata\local\programs\python\python37\lib\site-packages (from data-cleaning) (2.1.0)

WARNING: You are using pip version 21.0.1; however, version 21.1 is available.
You should consider upgrading via the 'c:\users\mural\appdata\local\programs\python\python37\python.exe -m pip install --upgrade pip' command.

# Importing Package

In [2]:
# data-cleaning package
from datacleaning import DataCleaning

# Using Default Parameters

In [3]:
from datacleaning import DataCleaning
import pandas as pd
dp = DataCleaning(file_upload='datasets/cancerdata.csv')
cleaned_df = dp.start_cleaning()

c:\users\mural\appdata\local\programs\python\python37\lib\site-packages\missingpy\missforest.py:528: UserWarning: No missing value located; returning original dataset.
  warnings.warn("No missing value located; returning original "

## Displaying Cleaned DataFrame as cleaned_df

In [4]:
display(cleaned_df)

,ID,Clump Thickness,Uniformity of Cell Size,Uniformity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleoli,Mitoses,Class
0,1241035.0,7.0,8,3,7,4,5,7,8,2,4
1,1107684.0,6.0,10,5,5,4,10,6,10,1,4
2,691628.0,8.0,6,4,10,10,1,3,5,1,4
3,1226612.0,7.0,5,6,3,3,8,7,4,1,4
4,1142706.0,5.0,10,10,10,6,10,6,5,2,4
...,...,...,...,...,...,...,...,...,...,...,...
736,752904.0,10.0,1,1,1,2,10,5,4,1,4
737,1296025.0,4.0,1,2,1,2,1,1,1,1,2
738,160296.0,5.0,8,8,10,5,10,8,10,3,4
739,1016277.0,6.0,8,8,1,3,4,3,7,1,2
740,492268.0,10.0,4,6,1,2,10,5,3,1,4